name: C/C++ CI

on:
  push:
    branches: [ "master", "**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make 
      run: make 
    - name: make report
      run: make report
    - name: make submodules
      run: make submodules
    - name: install brew make initialize
      run: curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh > ./install.sh && chmod +x ./install.sh && ./install.sh
    - name: make autogen
      run: make autogen
    - name: make configure
      run: make configure
    #- name: make -f Makefile all-am
    #  run: make -f Makefile all-am
